EXERCISE 5 

Importing Libraries :

In [122]:
import cv2 as cv
import numpy as np

Inputting Image :

In [123]:
lena_grayscale_image = cv.imread("lena_grayscale_hq.jpg",0)
print(lena_grayscale_image)

[[162 162 162 ... 170 155 128]
 [162 162 162 ... 170 156 128]
 [162 162 162 ... 170 154 128]
 ...
 [ 42  42  49 ... 104  99  98]
 [ 44  44  54 ... 104 104 108]
 [ 44  44  53 ... 104 105 108]]


Necessary Functions :

In [124]:
def integral_image(image):
    integral = np.zeros_like(image, dtype=np.uint32)
    integral[0, 0] = image[0, 0]

    # Compute the first row and column of the integral image
    for i in range(1, image.shape[0]):
        integral[i, 0] = integral[i - 1, 0] + image[i, 0]

    for j in range(1, image.shape[1]):
        integral[0, j] = integral[0, j - 1] + image[0, j]

    # Compute the rest of the integral image
    for i in range(1, image.shape[0]):
        for j in range(1, image.shape[1]):
            integral[i, j] = integral[i - 1, j] + integral[i, j - 1] - integral[i - 1, j - 1] + image[i, j]

    return integral

def box_filter(integral, w):
    output = np.zeros_like(integral, dtype=np.float32)
    half_w = w // 2

    for i in range(output.shape[0]):
        for j in range(output.shape[1]):
            x0, y0 = max(0, i - half_w), max(0, j - half_w)
            x1, y1 = min(i + half_w, integral.shape[0] - 1), min(j + half_w, integral.shape[1] - 1)

            sum_box = (
                integral[x1, y1] -
                (x0 > 0) * integral[x0 - 1, y1] -
                (y0 > 0) * integral[x1, y0 - 1] +
                (x0 > 0 and y0 > 0) * integral[x0 - 1, y0 - 1]
            )
            output[i, j] = np.float32(sum_box / (w * w))
    output = np.uint8(np.round(output))
    return output


def integralImage(image):
    m,n = image.shape
    integralImage = np.zeros((m,n) , dtype=np.int32)
    for i in range(m):
        for j in range(n):
            integralImage[i,j] = image[i,j]
            
            if i > 0 :
                integralImage[i,j] += integralImage[i-1,j]
            if j > 0 :
                integralImage[i,j] += integralImage[i,j-1]
            if i > 0 and j > 0 :
                integralImage[i,j] -= integralImage[i-1,j-1]
    bigIntegralImage = np.zeros( (m+1,n+1), dtype=np.int32)
    bigIntegralImage[1:,1:] = integralImage
    return bigIntegralImage

def open_cv_implementation_of_box_filter(image,filter_size):
      box_filter = np.ones((filter_size, filter_size), np.float32) / (filter_size * filter_size)
      border_type = cv.BORDER_CONSTANT
      opencv_filtered_image = cv.filter2D(image, -1, box_filter, borderType=border_type)
      return opencv_filtered_image

Q - 1 : Integral Image

In [125]:
integralOfLena = integralImage(lena_grayscale_image)
print(integralOfLena)
deneme=integral_image(lena_grayscale_image)
#print(deneme)

[[       0        0        0 ...        0        0        0]
 [       0      162      324 ...    69703    69858    69986]
 [       0      324      648 ...   139407   139718   139974]
 ...
 [       0    48468    96939 ... 32280873 32347309 32413825]
 [       0    48512    97027 ... 32340473 32407013 32473637]
 [       0    48556    97115 ... 32400074 32466719 32533451]]


In [126]:
opencvIntegralLena = cv.integral(lena_grayscale_image)
print(opencvIntegralLena)

[[       0        0        0 ...        0        0        0]
 [       0      162      324 ...    69703    69858    69986]
 [       0      324      648 ...   139407   139718   139974]
 ...
 [       0    48468    96939 ... 32280873 32347309 32413825]
 [       0    48512    97027 ... 32340473 32407013 32473637]
 [       0    48556    97115 ... 32400074 32466719 32533451]]


In [127]:
lenaIntegralWithoutZeroPadding = integralOfLena[1:,1:]
print(lenaIntegralWithoutZeroPadding)
print(lena_grayscale_image)

[[     162      324      486 ...    69703    69858    69986]
 [     324      648      972 ...   139407   139718   139974]
 [     486      972     1458 ...   209103   209568   209952]
 ...
 [   48468    96939   145645 ... 32280873 32347309 32413825]
 [   48512    97027   145787 ... 32340473 32407013 32473637]
 [   48556    97115   145928 ... 32400074 32466719 32533451]]
[[162 162 162 ... 170 155 128]
 [162 162 162 ... 170 156 128]
 [162 162 162 ... 170 154 128]
 ...
 [ 42  42  49 ... 104  99  98]
 [ 44  44  54 ... 104 104 108]
 [ 44  44  53 ... 104 105 108]]


Calculating the Difference :

In [128]:
print(abs(integralOfLena - opencvIntegralLena))
print(np.sum(abs(integralOfLena - opencvIntegralLena)))
# When multiplied with 100 :
print( 100 * abs(integralOfLena - opencvIntegralLena))
print(100 * np.sum(abs(integralOfLena - opencvIntegralLena)))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0


Q - 2 : Efficient Implementation of Box Filter using Integral Image :

OpenCV's Box Filter and It's Result :

In [129]:
boxfilter = open_cv_implementation_of_box_filter(lena_grayscale_image,3)
print(boxfilter)

[[ 72 108 108 ... 110 101  63]
 [108 162 162 ... 166 151  94]
 [108 162 162 ... 165 151  94]
 ...
 [ 29  46  48 ... 101 102  67]
 [ 29  46  48 ... 102 104  69]
 [ 20  31  33 ...  69  70  47]]


Our Box Filter Using Integral Image :

In [134]:
output=box_filter(deneme,3)
print(output)

C:\Users\Korhan\AppData\Local\Temp\ipykernel_21512\1556986300.py:49: RuntimeWarning: overflow encountered in scalar subtract
  integral[x1, y1] -
C:\Users\Korhan\AppData\Local\Temp\ipykernel_21512\1556986300.py:49: RuntimeWarning: overflow encountered in scalar add
  integral[x1, y1] -


[[ 72 108 108 ... 110 101  63]
 [108 162 162 ... 166 151  94]
 [108 162 162 ... 165 151  94]
 ...
 [ 29  46  48 ... 101 102  67]
 [ 29  46  48 ... 102 104  69]
 [ 20  31  33 ...  69  70  47]]


In [135]:
print(np.sum(abs(output - boxfilter)))

0


Q - 3 : Regular Box Filter versus using Integral Image : 

For 5x5 Box Filter :    In regular implementation, for one pixel there is 25 integer additions to sum the pixel values within the window and 1 floating- point divisions. On the other hand, in integral image implementation we have 4 integer additions and 1 floating point division for an output pixel. So we can say that using the integral image method can significantly reduce the computational load, especially for larger filter sizes.

Q - 4 : So what is the tradeoff ? Any downsides ?

The integral image method offers significant advantages in terms of computational efficiency, as it reduces the number of additions required to calculate the sum within a rectangular region. However, like any technique, it does have some downsides and limitations : 
Those are :
 
1 - Memory Overhead : This can be a concern especially for the larger images, it may impact memory usage.

2 - Preprocessing Overhead : Calculating the integral images requires an initial preprocessing step, which adds some overhead to the overall process. This may not be significant for a single image, but it can be a concern in real-time apps or when dealing with video streams.
    
3- Round Off Errors : The integral image method involves a division operation which can introduce round-off errors.Depending on the application, these errors may or may not be acceptable, but in this case , box filter has a division operation so this is a downthumb for both of them.